"""The "speak" step: a short second LLM call that rewrites a free-text draft so it reads like a person texting.

Why a second call: the main call (intent.classify_and_respond) decides intent, facts, booking slots AND writes the reply,
inside a JSON object, under a very long prompt. That is what keeps some replies stiff, long or translated-from-English.
This call does one thing -- say the same thing naturally -- with a short prompt and the business's native examples.

Only when needed (`needs_voice`): the draft has a defect a native reader notices that the deterministic steps can't fix
(Hindi/textbook words reply_polish has no swap for, an English sentence inside Nepali, a monologue for a short message,
volunteering "AI"). Filler endings, repeats and swappable words are already fixed for free by reply_polish, and a draft
in the wrong language is regenerated by the orchestrator's language check. Clean drafts are sent as they are, so most
turns pay nothing.

Never trusted blindly (`accept_rewrite`): every number, link, email and name in the draft must survive unchanged, no new
ones may appear, and the rewrite must be no worse by the same checks. Anything else -> the draft is sent instead.
The orchestrator also re-runs fact_validator and the language check on the rewrite."""

import logging
import re

from app.core.config import settings
from app.services.conversation.nepali_wordbank import find_issues, polish_reply, prompt_word_guide

logger = logging.getLogger(__name__)

_NEPALI = {"ne_roman", "mixed", "ne_deva"}
_EN_FUNCTION = {
    "the", "is", "are", "was", "you", "your", "we", "our", "to", "a", "an", "for", "and", "can", "it", "of", "on",
    "in", "with", "will", "would", "what", "when", "do", "does", "have", "has", "be", "this", "that", "there", "please",
    "if", "or", "at", "how", "my", "me", "us", "they", "not", "from", "just", "could",
}
_WORD = re.compile(r"[A-Za-z']+")
_NE_DIGITS = str.maketrans("०१२३४५६७८९", "0123456789")
_NUMBER = re.compile(r"\d[\d,]*(?:\.\d+)?")
_LINK = re.compile(r"https?://\S+|[\w.+-]+@[\w-]+\.[\w.]+")
_AI_WORD = re.compile(r"\b(ai|a\.i\.|artificial intelligence|chat ?bot|language model|virtual assistant)\b", re.IGNORECASE)
_ASKED_IDENTITY = re.compile(
    r"\b(bot|robot|ai|human|real person|manche|manxe|machine|computer)\b|मान्छे|रोबोट", re.IGNORECASE
)
_EXPLAIN = re.compile(
    r"\b(what is|what's|what are|explain|why|kina|k ho|ke ho|bhaneko k|vaneko k|k k|ke ke|kun kun|farak|difference|"
    r"barema|bare ma|janna)\b",
    re.IGNORECASE,
)


def _language_of_draft(language: str | None) -> str:
    return language or "en"


def needs_voice(draft: str, customer: str, language: str | None) -> list[str]:
    """Why this draft should be rewritten ([] = send it as is). Same defects the native judge's lint checks for."""
    reasons = []
    lang = _language_of_draft(language)
    if lang in _NEPALI:
        # Words reply_polish swaps on its own (aap -> tapai, kripaya -> dropped) don't need an LLM call; only what is
        # still wrong after that deterministic pass does.
        issues = find_issues(polish_reply(draft)[0])
        if any(kind == "hindi" for _, kind in issues):
            reasons.append("hindi words: " + ", ".join(w for w, k in issues if k == "hindi"))
        if any(kind in ("bookish", "error") for _, kind in issues):
            reasons.append("textbook/odd words: " + ", ".join(w for w, k in issues if k != "hindi"))
        if lang != "ne_deva":
            en = [w for w in _WORD.findall(draft.lower()) if w in _EN_FUNCTION]
            if len(en) >= 5:
                reasons.append("an English sentence inside a Nepali reply")
    customer_words, draft_words = len(customer.split()), len(draft.split())
    if customer_words <= 8 and draft_words > max(45, customer_words * 6) and not _EXPLAIN.search(customer) \
            and "\n-" not in draft and "\n•" not in draft:
        reasons.append(f"too long: {draft_words} words for a {customer_words}-word message")
    if _AI_WORD.search(draft) and not _ASKED_IDENTITY.search(customer):
        reasons.append("mentions being AI when nobody asked")
    return reasons


def _numbers(text: str) -> set[str]:
    return {n.replace(",", "").rstrip(".") for n in _NUMBER.findall(text.translate(_NE_DIGITS))}


def accept_rewrite(draft: str, rewritten: str, customer: str, language: str | None, protected: list[str]) -> str | None:
    """None if the rewrite is safe to send, else why it was rejected."""
    if not rewritten or not rewritten.strip():
        return "empty"
    if len(rewritten) > max(len(draft) * 1.15, len(draft) + 40):
        return "longer than the draft"
    if _numbers(rewritten) != _numbers(draft):
        return f"numbers changed: {sorted(_numbers(draft))} -> {sorted(_numbers(rewritten))}"
    if set(_LINK.findall(rewritten)) != set(_LINK.findall(draft)):
        return "links/emails changed"
    for name in protected:
        if name and name.lower() in draft.lower() and name.lower() not in rewritten.lower():
            return f"dropped {name!r}"
    before, after = needs_voice(draft, customer, language), needs_voice(rewritten, customer, language)
    if after and len(after) >= len(before):
        return "not better: " + "; ".join(after)
    return None


_SYSTEM = """You rewrite one chat reply from a business's front-desk assistant so it reads like a warm, competent \
local receptionist texting a customer. You get the customer's message, the assistant's previous reply and the draft.

Rules:
- Say the SAME thing: keep every fact exactly -- every number, price, time, date, name, link and email, written the \
same way. Add no new facts, promises, offers or questions. If the draft asks one question, keep that one question.
- Write in {language_rule}
- Answer first, short sentences, like a person typing on a phone. Usually 1-3 sentences; keep a list only if the \
draft has one.
- No filler endings ("let me know if...", "aru kehi chahiyo bhane bhannus"), no "As an AI", no apologies the draft \
doesn't have, no greeting if this isn't the first message.
- If the customer is upset or in pain, start with one short, genuine line of sympathy in their language.
- Never say you are a human. Don't bring up being AI unless the draft does because the customer asked.
{word_guide}
Output ONLY the rewritten reply text -- no quotes, no labels, no explanation."""

_LANGUAGE_RULES = {
    "ne_roman": "Romanized Nepali (Nepali in Latin letters), the way Nepali people text: everyday words, English "
                "words people really use (booking, price, slot), the customer's own spelling style (xa/vayo if they "
                "write that). Never Hindi words, never textbook Nepali, never Devanagari letters.",
    "mixed": "the same Nepali/English mix the customer uses, in Latin letters. Never Hindi words or textbook Nepali.",
    "ne_deva": "everyday spoken Nepali in Devanagari script, not textbook or office Nepali. Never Hindi words.",
    "en": "plain, friendly English.",
}


def _messages(draft, customer, previous_reply, language, reasons, exemplars) -> list[dict]:
    lang = _language_of_draft(language)
    system = _SYSTEM.format(
        language_rule=_LANGUAGE_RULES.get(lang, _LANGUAGE_RULES["en"]),
        word_guide=("\n" + prompt_word_guide() + "\n") if lang in ("ne_roman", "mixed") else "",
    )
    examples = [e.text for e in exemplars or [] if getattr(e, "text", None)][:5]
    parts = []
    if examples:
        parts.append("How this business's replies sound (tone only, not facts):\n" + "\n".join(f"- {t}" for t in examples))
    if previous_reply:
        parts.append(f"Assistant's previous reply:\n{previous_reply}")
    parts += [f"Customer's message:\n{customer}", f"Draft to rewrite:\n{draft}",
              "What's wrong with the draft: " + "; ".join(reasons)]
    return [{"role": "system", "content": system}, {"role": "user", "content": "\n\n".join(parts)}]


def _clean(text: str) -> str:
    text = (text or "").strip()
    text = re.sub(r"^(rewritten reply|reply|rewrite)\s*:\s*", "", text, flags=re.IGNORECASE)
    if len(text) >= 2 and text[0] == text[-1] and text[0] in "\"'“”":
        text = text[1:-1].strip()
    return text


def revoice(
    draft: str,
    *,
    customer: str,
    language: str | None,
    previous_reply: str | None,
    exemplars=None,
    protected: list[str] | None = None,
    chat=None,
) -> tuple[str, dict]:
    """(reply to send, info for the log). `chat`: the provider's chat(messages) -> str; defaults to the app's own."""
    mode = settings.voice_pass_mode
    info: dict = {"mode": mode}
    if mode == "off":
        return draft, info
    reasons = needs_voice(draft, customer, language)
    if mode == "always" and not reasons:
        reasons = ["make it sound natural"]
    info["reasons"] = reasons
    if not reasons:
        return draft, info
    if chat is None:
        from app.llm import get_chat_provider

        chat = get_chat_provider().chat
    try:
        rewritten = _clean(chat(_messages(draft, customer, previous_reply, language, reasons, exemplars)))
    except Exception as exc:  # noqa: BLE001 -- a failed polish must never fail the turn; the draft is still good
        info["error"] = f"{type(exc).__name__}: {exc}"[:200]
        return draft, info
    rejected = accept_rewrite(draft, rewritten, customer, language, protected or [])
    info["rewritten"] = rewritten
    if rejected:
        info["rejected"] = rejected
        return draft, info
    info["used"] = True
    return rewritten, info
