import logging

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.db.models.conversation import Message
from app.db.models.integration import Integration
from app.services.channels.instagram import InstagramChannelAdapter
from app.services.channels.meta_messaging_webhook import extract_incoming_text_messages

logger = logging.getLogger(__name__)

_adapter = InstagramChannelAdapter()

__all__ = ["extract_incoming_text_messages", "process_webhook_payload"]


def _resolve_integration(db: Session, *, ig_account_id: str) -> Integration | None:
    """Which tenant owns this Instagram professional account? Same pattern as
    Phase 26's page_id -> business_id resolution, reusing the same
    already-generic Integration model with zero schema changes:
    type="instagram", config={"ig_account_id": ..., "access_token": ...}.
    Returns the full Integration row (not just business_id) since
    send_message also needs this business's own per-account access token out
    of `config` — same reasoning as Messenger's page_access_token (Instagram
    has no platform-wide token either)."""
    return db.execute(
        select(Integration).where(
            Integration.type == "instagram",
            Integration.enabled.is_(True),
            Integration.config["ig_account_id"].astext == ig_account_id,
        )
    ).scalar_one_or_none()


def process_webhook_payload(db: Session, payload: dict) -> list[dict]:
    """The real webhook-processing pipeline — same shape as WhatsApp's/
    Messenger's process_webhook_payload, reusing the real, genuinely-shared
    entry[].messaging[] parser (meta_messaging_webhook.py) unchanged: for
    every real incoming text message, resolve its tenant, skip it if already
    processed (real idempotency, reusing Message.external_message_id's
    unique constraint — see the note below), run it through the exact same
    InstagramChannelAdapter -> Phase 8 orchestrator every other entry point
    uses, then send the real reply back (or a safe simulation).

    Idempotency column reuse, explicitly justified (same reasoning already
    applied to Messenger in Phase 26): Instagram message ids (opaque base64-
    ish strings, e.g. "aWdfZAG1lOm...") and WhatsApp/Messenger message ids
    are generated by different Meta subsystems with visibly different
    formats — cross-channel collision is not a real risk, so this reuses
    Message.external_message_id rather than adding a third column/migration
    for a namespace clash that isn't actually possible in practice. Even in a
    pathological collision, the failure mode is a dropped duplicate-looking
    message (logged, acked), never data corruption or cross-tenant leakage.

    Returns per-message outcomes for logging/testing only — NEVER sent back
    to Meta; the webhook route always acks with a plain 200 once past
    signature verification, per Meta's own documented webhook contract.
    """
    outcomes = []
    for incoming in extract_incoming_text_messages(payload):
        integration = _resolve_integration(db, ig_account_id=incoming["account_id"])
        if integration is None:
            logger.warning("instagram webhook: no business registered for ig_account_id=%s", incoming["account_id"])
            outcomes.append({"message_id": incoming["message_id"], "status": "unknown_ig_account_id"})
            continue
        business_id = integration.business_id

        already = db.execute(
            select(Message.id).where(Message.external_message_id == incoming["message_id"])
        ).scalar_one_or_none()
        if already is not None:
            logger.info("instagram webhook: duplicate message_id=%s, skipping", incoming["message_id"])
            outcomes.append({"message_id": incoming["message_id"], "status": "duplicate_skipped"})
            continue

        try:
            result = _adapter.receive_message(
                db,
                business_id=business_id,
                external_customer_ref=incoming["sender_id"],
                content=incoming["text"],
                external_message_id=incoming["message_id"],
            )
        except IntegrityError:
            # Real backstop for a genuine race between two concurrent
            # deliveries of the identical webhook — same "IntegrityError
            # means already handled" discipline as WhatsApp/Messenger.
            db.rollback()
            logger.info("instagram webhook: race caught by DB constraint for message_id=%s", incoming["message_id"])
            outcomes.append({"message_id": incoming["message_id"], "status": "duplicate_skipped"})
            continue

        if result is None:
            outcomes.append({"message_id": incoming["message_id"], "status": "business_not_found"})
            continue

        send_detail = _adapter.send_message(
            igsid=incoming["sender_id"],
            text=result["response"],
            ig_account_id=incoming["account_id"],
            access_token=(integration.config or {}).get("access_token") or "",
        )
        outcomes.append(
            {
                "message_id": incoming["message_id"],
                "status": "processed",
                "intent": result["intent"].value,
                "response": result["response"],
                "send_detail": send_detail,
            }
        )
    return outcomes
