import logging

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.db.models.conversation import Message
from app.db.models.integration import Integration
from app.services.channels.messenger import MessengerChannelAdapter

logger = logging.getLogger(__name__)

_adapter = MessengerChannelAdapter()


def extract_incoming_text_messages(payload: dict) -> list[dict]:
    """Walks Meta's real Messenger Platform webhook envelope shape —
    `entry[].messaging[]`, genuinely different from WhatsApp Cloud API's
    `entry[].changes[].value.messages[]` even though both are Meta products
    signed/verified the same way — and returns one normalized dict per real
    incoming TEXT message: {page_id, psid, message_id, text}.

    Deliberately tolerant, not a strict schema: this identical endpoint also
    delivers delivery/read receipts (`delivery`/`read` keys, no `message`),
    postbacks (button taps, no `message.text`), and echoes of the Page's OWN
    outgoing sends (`message.is_echo: true` — a Messenger-specific concept
    WhatsApp's webhook doesn't have, since Messenger echoes a Page's sent
    messages back through the same webhook) — all silently skipped, never a
    crash, since raising here would make Meta retry-storm us over events we
    don't act on (same discipline as WhatsApp's extract_incoming_text_messages).
    """
    results = []
    for entry in payload.get("entry", []) or []:
        page_id = entry.get("id")
        for event in entry.get("messaging", []) or []:
            message = event.get("message") or {}
            if not message or message.get("is_echo"):
                continue
            text = message.get("text")
            psid = (event.get("sender") or {}).get("id")
            message_id = message.get("mid")
            if not (page_id and psid and message_id and text):
                continue
            results.append({"page_id": page_id, "psid": psid, "message_id": message_id, "text": text})
    return results


def _resolve_integration(db: Session, *, page_id: str) -> Integration | None:
    """Which tenant owns this Meta Page? Extends Phase 22's
    phone_number_id -> business_id resolution pattern to Messenger's
    page_id, reusing the same already-generic Integration model
    (type/config JSONB) with zero schema changes: type="messenger",
    config={"page_id": ..., "page_access_token": ...}. Returns the full
    Integration row (not just business_id) since send_message also needs
    this business's own per-Page access token out of `config` — see the
    docstring on MessengerChannelAdapter.send_message for why that can't be
    a single global setting the way WHATSAPP_ACCESS_TOKEN is."""
    return db.execute(
        select(Integration).where(
            Integration.type == "messenger",
            Integration.enabled.is_(True),
            Integration.config["page_id"].astext == page_id,
        )
    ).scalar_one_or_none()


def process_webhook_payload(db: Session, payload: dict) -> list[dict]:
    """The real webhook-processing pipeline — same shape as WhatsApp's
    process_webhook_payload: for every real incoming text message, resolve
    its tenant, skip it if already processed (real idempotency, reusing
    Message.external_message_id's unique constraint — see the module-level
    note on collision risk below), run it through the exact same
    MessengerChannelAdapter -> Phase 8 orchestrator every other entry point
    uses, then send the real reply back (or a safe simulation).

    Idempotency column reuse, explicitly justified: Messenger message ids
    ("mid"s, e.g. "m_AG5Yf4wTvHqm9wPr...") and WhatsApp message ids
    ("wamid.xxx") are opaque strings generated by two different Meta
    subsystems with visibly different formats — cross-channel collision is
    not a real risk, so this reuses Message.external_message_id rather than
    adding a second column/migration for a namespace clash that isn't
    actually possible in practice. Even in a pathological collision, the
    failure mode is a dropped duplicate-looking message (logged, acked),
    never data corruption or cross-tenant leakage.

    Returns per-message outcomes for logging/testing only — NEVER sent back
    to Meta; the webhook route always acks with a plain 200 once past
    signature verification, per Meta's own documented webhook contract.
    """
    outcomes = []
    for incoming in extract_incoming_text_messages(payload):
        integration = _resolve_integration(db, page_id=incoming["page_id"])
        if integration is None:
            logger.warning("messenger webhook: no business registered for page_id=%s", incoming["page_id"])
            outcomes.append({"message_id": incoming["message_id"], "status": "unknown_page_id"})
            continue
        business_id = integration.business_id

        already = db.execute(
            select(Message.id).where(Message.external_message_id == incoming["message_id"])
        ).scalar_one_or_none()
        if already is not None:
            logger.info("messenger webhook: duplicate message_id=%s, skipping", incoming["message_id"])
            outcomes.append({"message_id": incoming["message_id"], "status": "duplicate_skipped"})
            continue

        try:
            result = _adapter.receive_message(
                db,
                business_id=business_id,
                external_customer_ref=incoming["psid"],
                content=incoming["text"],
                external_message_id=incoming["message_id"],
            )
        except IntegrityError:
            # Real backstop for a genuine race between two concurrent
            # deliveries of the identical webhook — same "IntegrityError
            # means already handled" discipline as WhatsApp/Phase 18/19.
            db.rollback()
            logger.info("messenger webhook: race caught by DB constraint for message_id=%s", incoming["message_id"])
            outcomes.append({"message_id": incoming["message_id"], "status": "duplicate_skipped"})
            continue

        if result is None:
            outcomes.append({"message_id": incoming["message_id"], "status": "business_not_found"})
            continue

        send_detail = _adapter.send_message(
            psid=incoming["psid"],
            text=result["response"],
            page_access_token=(integration.config or {}).get("page_access_token") or "",
        )
        outcomes.append(
            {
                "message_id": incoming["message_id"],
                "status": "processed",
                "intent": result["intent"].value,
                "response": result["response"],
                "send_detail": send_detail,
            }
        )
    return outcomes
