"""phase 34 subscription plan entitlement

Revision ID: 1b540231b5fa
Revises: 5aa289d64419
Create Date: 2026-09-06 04:45:59.305105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b540231b5fa'
down_revision = '5aa289d64419'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Autogenerate's add_column below assumes the native Postgres ENUM type
    # already exists — true when a table is first CREATEd (SQLAlchemy emits
    # the type inline), but NOT true for ALTER TABLE ADD COLUMN on an
    # existing table. Must create it explicitly first, or the ADD COLUMN
    # below fails with "type business_plan does not exist" (confirmed live).
    sa.Enum('FREE', 'PREMIUM', name='business_plan').create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_users', sa.Column('is_superadmin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('businesses', sa.Column('plan', sa.Enum('FREE', 'PREMIUM', name='business_plan'), server_default='FREE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'plan')
    op.drop_column('business_users', 'is_superadmin')
    # ### end Alembic commands ###
    # Autogenerate's drop_column above does not drop the native Postgres ENUM
    # type backing this column — without this it would leak past downgrade
    # and collide on the next upgrade (same fix the initial schema migration
    # already applies for its own enum columns; see 371630166e11).
    sa.Enum(name='business_plan').drop(op.get_bind(), checkfirst=True)
