"""sms premium feature

Revision ID: 3d021b71559b
Revises: f00944fc83c2
Create Date: 2026-09-04 03:50:30.949102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d021b71559b'
down_revision = 'f00944fc83c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('sms_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('sms_opt_in', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'sms_opt_in')
    op.drop_column('businesses', 'sms_enabled')
    # ### end Alembic commands ###
