"""training room

Revision ID: 5ee479b338d6
Revises: a9aac190cac8
Create Date: 2026-09-04 09:23:53.817663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee479b338d6'
down_revision = 'a9aac190cac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_questions',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('asked_by', sa.UUID(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('corrected_answer', sa.Text(), nullable=True),
    sa.Column('correction_knowledge_document_id', sa.UUID(), nullable=True),
    sa.Column('feedback_by', sa.UUID(), nullable=True),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asked_by'], ['business_users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['correction_knowledge_document_id'], ['knowledge_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feedback_by'], ['business_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_questions_business_id'), 'training_questions', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_questions_business_id'), table_name='training_questions')
    op.drop_table('training_questions')
    # ### end Alembic commands ###
