"""business currency field

Revision ID: 68c42ea77aff
Revises: 994c50bf2428
Create Date: 2026-09-06 16:06:19.551388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c42ea77aff'
down_revision = '994c50bf2428'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'currency')
    # ### end Alembic commands ###
