"""phase 38 business widget branding

Revision ID: 7777493e36ff
Revises: a0ec080bbff5
Create Date: 2026-09-06 11:06:49.671634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7777493e36ff'
down_revision = 'a0ec080bbff5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('brand_color', sa.String(length=7), server_default='#2563eb', nullable=False))
    op.add_column('businesses', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'logo_url')
    op.drop_column('businesses', 'brand_color')
    # ### end Alembic commands ###
