"""whatsapp message idempotency

Revision ID: 7bf5f90d0620
Revises: 8e2dd971ff6f
Create Date: 2026-09-04 10:18:56.663348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf5f90d0620'
down_revision = '8e2dd971ff6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('external_message_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_messages_external_message_id', 'messages', ['external_message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_messages_external_message_id', 'messages', type_='unique')
    op.drop_column('messages', 'external_message_id')
    # ### end Alembic commands ###
