"""channel identities

Revision ID: 8e2dd971ff6f
Revises: 5ee479b338d6
Create Date: 2026-09-04 09:45:52.085536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2dd971ff6f'
down_revision = '5ee479b338d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_identities',
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id', 'business_id'], ['customers.id', 'customers.business_id'], name='fk_channel_identities_customer_same_tenant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'channel', 'external_ref', name='uq_channel_identities_business_channel_ref')
    )
    op.create_index(op.f('ix_channel_identities_business_id'), 'channel_identities', ['business_id'], unique=False)
    op.create_index(op.f('ix_channel_identities_customer_id'), 'channel_identities', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_identities_customer_id'), table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_business_id'), table_name='channel_identities')
    op.drop_table('channel_identities')
    # ### end Alembic commands ###
