"""phase 44 payment collection esewa khalti deposit fields

Revision ID: 8ef2989e7fca
Revises: 68c42ea77aff
Create Date: 2026-09-13 02:59:48.501418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef2989e7fca'
down_revision = '68c42ea77aff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='payment_status'), server_default='PENDING', nullable=False),
    sa.Column('gateway_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_url', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id', 'business_id'], ['appointments.id', 'appointments.business_id'], name='fk_payments_appointment_same_tenant'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', name='uq_payments_appointment_id')
    )
    op.create_index(op.f('ix_payments_appointment_id'), 'payments', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_payments_business_id'), 'payments', ['business_id'], unique=False)
    op.add_column('businesses', sa.Column('payment_collection_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('businesses', sa.Column('payment_provider', sa.String(length=20), nullable=True))
    op.add_column('services', sa.Column('deposit_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('services', sa.Column('deposit_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'deposit_percentage')
    op.drop_column('services', 'deposit_enabled')
    op.drop_column('businesses', 'payment_provider')
    op.drop_column('businesses', 'payment_collection_enabled')
    op.drop_index(op.f('ix_payments_business_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_appointment_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
