"""phase 40 google calendar sync fields

Revision ID: 994c50bf2428
Revises: 7777493e36ff
Create Date: 2026-09-06 11:37:50.165749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994c50bf2428'
down_revision = '7777493e36ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('calendar_sync_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'calendar_sync_status')
    op.drop_column('appointments', 'google_calendar_event_id')
    # ### end Alembic commands ###
