"""human handoff open constraint

Revision ID: a9aac190cac8
Revises: ea79c3e1164f
Create Date: 2026-09-04 08:56:52.724788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9aac190cac8'
down_revision = 'ea79c3e1164f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_human_handoffs_conversation_id_open', 'human_handoffs', ['conversation_id'], unique=True, postgresql_where=sa.text('resolved_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_human_handoffs_conversation_id_open', table_name='human_handoffs', postgresql_where=sa.text('resolved_at IS NULL'))
    # ### end Alembic commands ###
