"""knowledge base ingestion

Revision ID: aa23ade02a4c
Revises: be989d8a4be3
Create Date: 2026-09-03 18:09:00.331655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa23ade02a4c'
down_revision = 'be989d8a4be3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('content', sa.Text(), server_default='', nullable=False))
    op.add_column('knowledge_documents', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'approved_at')
    op.drop_column('knowledge_documents', 'content')
    # ### end Alembic commands ###
