"""phase 45 appointment reminders

Revision ID: b86c6c77494c
Revises: 8ef2989e7fca
Create Date: 2026-09-13 03:47:05.377923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86c6c77494c'
down_revision = '8ef2989e7fca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_appointments_reminder_sent_at'), 'appointments', ['reminder_sent_at'], unique=False)
    op.add_column('businesses', sa.Column('reminder_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('businesses', sa.Column('reminder_minutes_before', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'reminder_minutes_before')
    op.drop_column('businesses', 'reminder_enabled')
    op.drop_index(op.f('ix_appointments_reminder_sent_at'), table_name='appointments')
    op.drop_column('appointments', 'reminder_sent_at')
    # ### end Alembic commands ###
