"""business configuration

Revision ID: be989d8a4be3
Revises: 5588d67a7cf6
Create Date: 2026-09-03 17:54:16.500337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be989d8a4be3'
down_revision = '5588d67a7cf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours_exceptions',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('closed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('closed OR (open_time IS NOT NULL AND close_time IS NOT NULL AND close_time > open_time)', name='ck_business_hours_exceptions_valid_range'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'date', name='uq_business_hours_exceptions_business_date')
    )
    op.create_index(op.f('ix_business_hours_exceptions_business_id'), 'business_hours_exceptions', ['business_id'], unique=False)
    op.add_column('business_hours', sa.Column('closed', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('business_hours', 'open_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('business_hours', 'close_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.create_unique_constraint('uq_business_hours_business_day', 'business_hours', ['business_id', 'day_of_week'])
    # Not autogenerated: alembic's default autogenerate does not diff CHECK constraints
    # on existing tables (only on newly-created ones).
    op.create_check_constraint(
        'ck_business_hours_valid_range',
        'business_hours',
        'closed OR (open_time IS NOT NULL AND close_time IS NOT NULL AND close_time > open_time)',
    )
    op.add_column('businesses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('languages', postgresql.ARRAY(sa.String(length=16)), nullable=True))
    op.add_column('businesses', sa.Column('tone', sa.String(length=100), nullable=True))
    op.add_column('services', sa.Column('staff_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_services_staff_id'), 'services', ['staff_id'], unique=False)
    op.create_foreign_key('fk_services_staff_same_tenant', 'services', 'staff', ['staff_id', 'business_id'], ['id', 'business_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_services_staff_same_tenant', 'services', type_='foreignkey')
    op.drop_index(op.f('ix_services_staff_id'), table_name='services')
    op.drop_column('services', 'staff_id')
    op.drop_column('businesses', 'tone')
    op.drop_column('businesses', 'languages')
    op.drop_column('businesses', 'description')
    op.drop_constraint('ck_business_hours_valid_range', 'business_hours', type_='check')
    op.drop_constraint('uq_business_hours_business_day', 'business_hours', type_='unique')
    op.alter_column('business_hours', 'close_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('business_hours', 'open_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_column('business_hours', 'closed')
    op.drop_index(op.f('ix_business_hours_exceptions_business_id'), table_name='business_hours_exceptions')
    op.drop_table('business_hours_exceptions')
    # ### end Alembic commands ###
