"""appointment booking race protection

Revision ID: c54ef41b197d
Revises: ea1b824909b1
Create Date: 2026-09-04 01:26:58.873515

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'c54ef41b197d'
down_revision = 'ea1b824909b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Hand-added below: autogenerate only picked up the plain index (see the
    # single auto-generated line) — it doesn't diff CREATE EXTENSION, functions,
    # or ExcludeConstraint at all, so those are written by hand, same as the
    # CheckConstraint gap hand-fixed in be989d8a4be3.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # A GiST index expression must be IMMUTABLE; the built-in timestamptz + interval
    # operator is only STABLE (interval can carry month/day components whose result
    # depends on the session's TimeZone setting). This wrapper is safe to declare
    # IMMUTABLE anyway because every caller only ever passes a pure-minutes interval
    # (never months/days), which has no such ambiguity — see app/db/models/appointment.py.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION appointment_range(scheduled_at timestamptz, duration_minutes int)
        RETURNS tstzrange AS $$
          SELECT tstzrange(scheduled_at, scheduled_at + (duration_minutes * interval '1 minute'), '[)');
        $$ LANGUAGE sql IMMUTABLE STRICT
        """
    )

    # ### auto generated by Alembic ###
    op.create_index('ix_appointments_business_id_scheduled_at', 'appointments', ['business_id', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###

    # The actual race-condition guarantee: two overlapping appointments for the same
    # (business_id, resolved staff resource) can never both commit. A NULL staff_id
    # coalesces to business_id (an unassigned booking occupies one shared per-business
    # resource — see booking_service.py). Cancelled appointments never block a slot.
    # 'CANCELLED' (uppercase): SQLAlchemy's Enum(AppointmentStatus) stores the Python
    # enum MEMBER NAME as the Postgres enum label by default, not member.value —
    # confirmed against the real DB (`SELECT enumlabel FROM pg_enum ...`) before
    # writing this, not assumed.
    op.execute(
        """
        ALTER TABLE appointments ADD CONSTRAINT excl_appointments_no_overlap
        EXCLUDE USING gist (
            business_id WITH =,
            COALESCE(staff_id, business_id) WITH =,
            appointment_range(scheduled_at, duration_minutes) WITH &&
        ) WHERE (status <> 'CANCELLED'::appointment_status)
        """
    )


def downgrade() -> None:
    op.execute("ALTER TABLE appointments DROP CONSTRAINT excl_appointments_no_overlap")

    # ### auto generated by Alembic ###
    op.drop_index('ix_appointments_business_id_scheduled_at', table_name='appointments')
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION IF EXISTS appointment_range(timestamptz, int)")
    # btree_gist is left installed on downgrade: it's a shared, harmless extension
    # (no data of ours lives in it) and other future features may want it too —
    # same reasoning Phase 2 applied to leaving the `vector` extension installed.
