"""group booking id

Revision ID: e165f433cce9
Revises: c54ef41b197d
Create Date: 2026-09-04 02:34:38.655053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e165f433cce9'
down_revision = 'c54ef41b197d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('group_booking_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_appointments_group_booking_id'), 'appointments', ['group_booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_group_booking_id'), table_name='appointments')
    op.drop_column('appointments', 'group_booking_id')
    # ### end Alembic commands ###
