"""conversation summarization fields

Revision ID: ea1b824909b1
Revises: aa23ade02a4c
Create Date: 2026-09-03 19:07:52.633915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1b824909b1'
down_revision = 'aa23ade02a4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('summarized_message_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summarized_message_count')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
