"""automatic follow-up

Revision ID: ea79c3e1164f
Revises: 3d021b71559b
Create Date: 2026-09-04 08:15:03.874768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea79c3e1164f'
down_revision = '3d021b71559b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('follow_ups_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('follow_ups', sa.Column('channel', sa.String(length=50), nullable=True))
    op.add_column('follow_ups', sa.Column('trigger_message_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_follow_ups_conversation_id', 'follow_ups', ['conversation_id'])
    op.create_foreign_key(
        'fk_follow_ups_trigger_message_id', 'follow_ups', 'messages', ['trigger_message_id'], ['id'], ondelete='SET NULL'
    )
    op.add_column('messages', sa.Column('detected_intent', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'detected_intent')
    op.drop_constraint('fk_follow_ups_trigger_message_id', 'follow_ups', type_='foreignkey')
    op.drop_constraint('uq_follow_ups_conversation_id', 'follow_ups', type_='unique')
    op.drop_column('follow_ups', 'trigger_message_id')
    op.drop_column('follow_ups', 'channel')
    op.drop_column('businesses', 'follow_ups_enabled')
    # ### end Alembic commands ###
