"""phase 46 qr checkin

Revision ID: ee2ef4fc6cbe
Revises: b86c6c77494c
Create Date: 2026-09-13 11:07:21.935938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2ef4fc6cbe'
down_revision = 'b86c6c77494c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('checkin_token', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('appointments', sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_appointments_checkin_token', 'appointments', ['checkin_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_appointments_checkin_token', 'appointments', type_='unique')
    op.drop_column('appointments', 'checked_in_at')
    op.drop_column('appointments', 'checkin_token')
    # ### end Alembic commands ###
