"""notification dispatch fields

Revision ID: f00944fc83c2
Revises: e165f433cce9
Create Date: 2026-09-04 02:59:20.423901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00944fc83c2'
down_revision = 'e165f433cce9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('event_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

    # Not autogenerate-detected: adding an enum VALUE isn't a column diff.
    # 'SIMULATED' uppercase to match this project's established convention —
    # SQLAlchemy's Enum(NotificationStatus) stores the Python member NAME as the
    # Postgres label, not member.value (see the Phase 10 appointment_status bug
    # in PHASE_STATUS.md for how this was discovered). Safe to run inside this
    # migration's transaction on Postgres 12+ as long as the new value is never
    # read/written in the same transaction that adds it — it isn't here.
    op.execute("ALTER TYPE notification_status ADD VALUE IF NOT EXISTS 'SIMULATED'")


def downgrade() -> None:
    # Postgres has no ALTER TYPE ... DROP VALUE. Reversing requires rebuilding
    # the enum type from scratch: any row already marked SIMULATED is
    # remapped to FAILED first (SIMULATED never claimed real delivery, so
    # FAILED is the honest downgrade target, not SENT).
    op.execute("UPDATE notifications SET status = 'FAILED' WHERE status = 'SIMULATED'")
    op.execute("ALTER TYPE notification_status RENAME TO notification_status_old")
    op.execute("CREATE TYPE notification_status AS ENUM ('QUEUED', 'SENT', 'DELIVERED', 'FAILED')")
    op.execute(
        "ALTER TABLE notifications ALTER COLUMN status TYPE notification_status "
        "USING status::text::notification_status"
    )
    op.execute("DROP TYPE notification_status_old")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'event_type')
    # ### end Alembic commands ###
