"""phase 46 in person payment collection

Revision ID: fc8e1d0ac457
Revises: ee2ef4fc6cbe
Create Date: 2026-09-13 11:29:49.065776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8e1d0ac457'
down_revision = 'ee2ef4fc6cbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('collected_in_person_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payments', sa.Column('collected_in_person_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'collected_in_person_at')
    op.drop_column('payments', 'collected_in_person_amount')
    # ### end Alembic commands ###
